# Terminal
bindsym $mod+Return exec $term 

# Kill window
bindsym $mod+q kill 

# Launcher 
bindsym $mod+d exec $menu 

# Reload 
bindsym $mod+Shift+c reload 

# Lock screen 
bindsym $mod+alt+l exec swaylock

# Exit 
bindsym $mod+Shift+e exec wlogout -p layer-shell
