# GTK & Themes 
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_DESKTOP=sway

exec_always {
    gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Blue-Dark"
    gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Ice"
    gsettings set org.gnome.desktop.interface cursor-size 24
}


# Cursor 
seat seat0 xcursor_theme Bibata-Modern-Ice 24

# Border & Colors 
default_border pixel 2
default_floating_border pixel 2

# Catppuccin Mocha colors
# class                 border     bg         text       indicator  child_border
client.focused          #cba6f7    #cba6f7    #1e1e2e    #f5c2e7    #cba6f7
client.focused_inactive #313244    #313244    #cdd6f4    #313244    #313244
client.unfocused        #313244    #1e1e2e    #6c7086    #313244    #313244
client.urgent           #f38ba8    #f38ba8    #1e1e2e    #f38ba8    #f38ba8

